name: desafio_capyba2
description: Um aplicativo Flutter com backend Firebase.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  image_picker: ^0.8.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
